artifacts_root: artifacts 

data_ingestion:
  root_dir: artifacts/data_ingestion 
  source_URL: https://github.com/Shouvik-7/data/raw/main/CarPrice_Assignment.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion 